<?php

namespace App\ComprasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DelegacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelegacionRepository extends EntityRepository
{
}
