<?php

namespace App\ComprasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LineaPedidoElementoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaPedidoElementoRepository extends EntityRepository
{
}
