<?php

namespace App\ComprasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Pedido_elementoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoElementoRepository extends EntityRepository
{
}
