<?php

namespace App\ComprasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Tipo_compraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoCompraRepository extends EntityRepository
{
 
    
    public function calcularTipoCompra($monto){
        $tipos = $this->getDoctrine()->getEntityManager()
        ->getRepository('AppComprasBundle:TipoCompra')
        ->findAll();
        
        foreach ($tipos as $tipo) {
            if(($tipo->getMontoMin()<$monto)&&($tipo->getMontoMax()<$monto)){
                return $tipo;
            }
        }
    }
    
}
