services:
    sonata.admin.delegacion:
        class: App\ComprasBundle\Admin\DelegacionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Entidades", label: "Delegacion" }
        arguments:
            - ~
            - App\ComprasBundle\Entity\Delegacion
            - ~
        calls:
            - [ setTranslationDomain, [AppComprasBundle]]
            
    sonata.admin.ubicacion:
        class: App\ComprasBundle\Admin\UbicacionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Entidades", label: "Ubicacion" }
        arguments:
            - ~
            - App\ComprasBundle\Entity\Ubicacion
            - ~
        calls:
            - [ setTranslationDomain, [AppComprasBundle]]
            
    sonata.admin.articulo:
        class: App\ComprasBundle\Admin\ArticuloAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Entidades", label: "Articulo" }
        arguments:
            - ~
            - App\ComprasBundle\Entity\Articulo
            - ~
        calls:
            - [ setTranslationDomain, [AppComprasBundle]]
   
#    sonata.admin.pedidoelemento:
#        class: App\ComprasBundle\Admin\PedidoElementoAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: "Entidades", label: "PedidoElemento" }
#        arguments:
#            - ~
#            - App\ComprasBundle\Entity\PedidoElemento
#            - ~
#        calls:
#            - [ setTranslationDomain, [AppComprasBundle]]
    
    sonata.admin.tipocompra:
        class: App\ComprasBundle\Admin\TipoCompraAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Entidades", label: "TipoCompra" }
        arguments:
            - ~
            - App\ComprasBundle\Entity\TipoCompra
            - ~
        calls:
            - [ setTranslationDomain, [AppComprasBundle]]
            
    sonata.admin.usuario:
        class: App\ComprasBundle\Admin\UsuarioAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Entidades", label: "Usuario" }
        arguments:
            - ~
            - App\ComprasBundle\Entity\Usuario
            - ~
        calls:
            - [ setTranslationDomain, [AppComprasBundle]]
            
    sonata.admin.estadopedido:
        class: App\ComprasBundle\Admin\EstadoPedidoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Entidades", label: "EstadoPedido" }
        arguments:
            - ~
            - App\ComprasBundle\Entity\EstadoPedido
            - ~
        calls:
            - [ setTranslationDomain, [AppComprasBundle]]

    app_compras.admin.pedido_elemento:
        class: App\ComprasBundle\Admin\PedidoElementoAdmin
        arguments: [~, App\ComprasBundle\Entity\PedidoElemento, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Entidades", label: PedidoElemento}

    app_compras.admin.linea_pedido_elemento:
        class: App\ComprasBundle\Admin\LineaPedidoElementoAdmin
        arguments: [~, App\ComprasBundle\Entity\LineaPedidoElemento, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Entidades", label: LineaPedidoElemento}
